### ISSUE TITLE
Nuget package not updated since Dec 2014

### ISSUE THREAD

**Issue by ma499** [grumpydev/TinyIoC#107]
The latest package published at nuget.org is dated 17 Dec 2014. There have been various commits to master since then, including features such as core CLR compatibility.

Is it possible to get a newer nuget package version?

**Comment by Tdue21** [comment]
+1

Don't really know what else to say, an updated nuget would be sweet.

**Comment by niemyjski** [comment]
We'll get this updated with the next release.
