### ISSUE TITLE
Has .net core 1.1 broken Tiny ?

### ISSUE THREAD

**Issue by bbsimonbb** [grumpydev/TinyIoC#112]
Has .net core 1.1 broken TinyIoC? Integrating Tiny into an empty .net core app in VS2017 produces a rake of errors, mostly in the serialization section that should probably be switched off. But the #serialization preprocessor directive is not getting unset, likely because the existing preprocessor variables NETSTANDARD1_0 --> NETSTANDARD1_6 are not present. I tried adding a test for NETSTANDARD1_7, with no luck.

What NETSTANDARD is .net core 1.1? [This page](https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/libraries) should list it, but doesn't. Has anyone else struck this?

[Related Stack question](http://stackoverflow.com/questions/42999052/tinyioc-not-integrating-in-a-net-core-app-1-1)

**Comment by xfigue** [comment]
Same here.
+1

**Comment by niemyjski** [comment]
The lowest I've tested this on is .net standard 1.2 in production. .net standard does not mean .net core. You may need to set some compiler directives like NETSTANDARD1_5 and bring in a nuget package or two. If you need any more information please let me know.
