### ISSUE TITLE
Condition Looks odd..

### ISSUE THREAD

**Issue by dazinator** [grumpydev/TinyIoC#117]
https://github.com/grumpydev/TinyIoC/blob/c706619f8c5711529f2ce67566da906596ff9637/src/TinyIoC/TinyIoC.cs#L4249
 Just wondering - If I have grasped the intent of the code correctly, should that last bit on the line above not be `&& !NETSTANDARD1_6` or perhaps `|| NETSTANDARD1_6` ?

**Comment by dazinator** [comment]
The reason I say that is because at the moment this is resulting in a duplicate type being incuded when targeting `net45` and `netstandard1.6`

**Comment by niemyjski** [comment]
Yeah, we'll have to update this for the other net standards as well. We probably need to do a poll and see what versions we still need to support and support only that.
