### ISSUE TITLE
Why nuget install doesn't create a refencable TinyIOC dll ?

### ISSUE THREAD

**Issue by fstarred** [grumpydev/TinyIoC#120]
With a shared dll it's possible to share same dll through separated projects and wouldn't be required to bring same TinyIOC.cs code on all projects.

**Comment by niemyjski** [comment]
Currently it only does a source file (https://github.com/grumpydev/TinyIoC#overview) but it could be added value to Brin in a nuget package. You should only have to bring it into one of your shared assemblies and reference it from your other ones.
