### ISSUE TITLE
Platform compatibility

### ISSUE THREAD

**Issue by badevilerror** [grumpydev/TinyIoC#123]
I couldn't find any info about platform compatibility in the wiki.

I would like to use TinyIoC for a Unity game potentially targeting pc/mac/linux/xbox/ps4/android/ios.

I'm guessing pc, mac and linux should be no problem - at least it is working fine so far. I don't have other devices yet to make any tests.

Are those platforms (mobile and console) officially (or not so officially) supported by TinyIoC and  TinyMessenger?

**Comment by niemyjski** [comment]
We have it working on .net standard and .net 4.5 full framework on linux, macOS and windows without issue.

**Comment by jmrnilsson** [comment]
Ran into namespace not being available after nuget install on .net core 2.1 with Visual Studio Pro. Maybe there is something more to this.

**Comment by niemyjski** [comment]
We are also targeting .net standard 2.0 here (https://github.com/exceptionless/Exceptionless.Net/tree/master/src/Exceptionless). Can you see what you are missing by looking at our csproj? It would be really nice to drop some target frameworks and clean up the code a bit.

**Comment by kraeg75** [comment]
I can't seem to get VS 2019 .Net Standard 2.0 to recognise the TinyIoC namespace at all.  Works fine in .Net Framework.  I tried starting a brand new project, added the TinyIoC NuGet package (v1.3.0) and all I see is "The name TinyIoCContainer' does not exist in the current context" and "Cannot resolve symbol 'TinyIoCContainer'".

**Comment by kraeg75** [comment]
Oh!  Now I see...  The .Net Framework project has had a file named TinyIoC.cs added to it.  That didn't happen for my .Net Standard projects.  Should it have?  Presumably I can just copy it over?

**Comment by niemyjski** [comment]
I should delist the alpha package (https://github.com/grumpydev/TinyIoC/issues/136) If anyone has some time to help look into this that would be awesome.

**Comment by jmrnilsson** [comment]
Sorry. No time anytime soon. Also, these namespace pragmas.. Perhaps things settles more clearly in future in the DNX, NetCore-1-2-3 vs NetStandard-world.
