### ISSUE TITLE
NuGet Support & Build System

### ISSUE THREAD

**Issue by waliarubal** [grumpydev/TinyIoC#134]
The NuGet package you have published is ages old, kindly update the package. VS2019 suggested using "Nancy" package when using container and other classes in code. I have to use it as of now, please update your package. Maybe use some automated build system for pushing stuff to NuGet automatically.

**Comment by niemyjski** [comment]
We'd be willing to accept GitHub actions support as a PR. I'll see what we can do to update this package.

**Comment by grumpydev** [comment]
> We'd be willing to accept GitHub actions support as a PR. I'll see what we can do to update this package.

I can give you access to the package in nuget if I haven't already.

**Comment by niemyjski** [comment]
Can you please add me to nuget: `niemyjski`

**Comment by niemyjski** [comment]
I just did a bunch of work to get it working on Mac and GitHub actions (clone and run) as well as the new project system. Still more todo.
