### ISSUE TITLE
QUESTION: Can I disable property injection?

### ISSUE THREAD

**Issue by EvilBeaver** [grumpydev/TinyIoC#142]
I don't want property injections on object creation. How can I disable it?

**Comment by grumpydev** [comment]
Property injection doesn't happen automatically, you have to manually called "BuildUp" to do it, so it is "disabled" if you're just using ctor injection.

**Comment by EvilBeaver** [comment]
Thanks. I was confused by a phrase in wiki: "Any public read/write property that we can resolve, that isn't already set to a value, is resolved by the container".
