### ISSUE TITLE
Optimization of objects allocation during auto-registration of TinyIoC

### ISSUE THREAD

**Issue by AlexanderMy** [grumpydev/TinyIoC#151]
Optimization of objects allocation during auto-registration of TinyIoC.
During work on our project, I found that TinyIoC is allocating a lot of objects during class initialization. 
I created a branch with changes and would be glad to push it and create pull request.

**Comment by niemyjski** [comment]
That would be awesome. Can you also please ensure you have latest as we also just merged in (https://github.com/grumpydev/TinyIoC/pull/147)

**Comment by AlexanderMy** [comment]
I created a pull request: https://github.com/grumpydev/TinyIoC/pull/152

**Comment by niemyjski** [comment]
Thanks for the PR!
