### ISSUE TITLE
ambiguous call between methods

### ISSUE THREAD

**Issue by KiMargin** [grumpydev/TinyIoC#43]
I am trying to build a project with TinyIoC. (Win8, VS2012 sp3)

And get three errors:
Error   561 The call is ambiguous between the following methods or properties: 
'TinyIoC.AssemblyExtensions.SafeGetTypes(System.Reflection.Assembly)' and 'TinyIoC.AssemblyExtensions.SafeGetTypes(System.Reflection.Assembly)' 

Error   583 The call is ambiguous between the following methods or properties: 'TinyIoC.TypeExtensions.GetGenericMethod(System.Type, System.Reflection.BindingFlags, string, System.Type[], System.Type[])' and 'TinyIoC.TypeExtensions.GetGenericMethod(System.Type, System.Reflection.BindingFlags, string, System.Type[], System.Type[])'

Error   607 The call is ambiguous between the following methods or properties: 'TinyIoC.TypeExtensions.GetGenericMethod(System.Type, System.Reflection.BindingFlags, string, System.Type[], System.Type[])' and 'TinyIoC.TypeExtensions.GetGenericMethod(System.Type, System.Reflection.BindingFlags, string, System.Type[], System.Type[])'

**Comment by ThomasWeiss** [comment]
Just to help people that may run in the same issue, it happened to me in a project that was including both TinyIoC and Nancy... Took me quite a while to figure it out!

**Comment by jgillich** [comment]
@ThomasWeiss How did you solve it? Use `Nancy.TinyIoC`?

**Comment by ThomasWeiss** [comment]
@jgillich Yes
