### ISSUE TITLE
ResolveAll() and ResolveAll<T>() do not return the same results

### ISSUE THREAD

**Issue by powerdude** [grumpydev/TinyIoC#63]
Hello,

If i have the following:

```
            var c = new TinyIoCContainer();
            c.Register<IXFormsApp>(App);
            var results3 = c.ResolveAll(typeof(IXFormsApp)).ToList();
            var results4 = c.ResolveAll<IXFormsApp>().ToList();
```

results3.Count <> results4.Count;

Shouldn't they be equal?

**Comment by grayyang** [comment]
Seems the implementation of ResolveAll(Type resolveType) does not match its description

`/// <summary>
/// Returns all registrations of a type, both named and unnamed
/// </summary>
/// <param name="resolveType">Type to resolveAll</param>
/// <returns>IEnumerable</returns>
public IEnumerable<object> ResolveAll(Type resolveType)
{
      return ResolveAll(resolveType, false);
}`

should be 
`return ResolveAll(resolveType, true);`
