### ISSUE TITLE
GetTypeConstructors method disregards non-public constructors.

### ISSUE THREAD

**Issue by r3db** [grumpydev/TinyIoC#71]
Hey :) I was wondering if this is by design or not.
And if so what were the considerations that lead to such decision being made.

In a nutshell TinyIoC will fail to resolve a type if it does not find a public constructor, (which seems reasonable). ;)

Why resolve a type with a private constructor?
If it's private it's not meant to be instantiated by anyone, except the class owner, (we can all agree on that).

But what about when the constructor is **internal**.
Let's say you have an `MVC` controller, it doesn't make sense to make that type public, (you don't really want to expose it, you only consume the controller internally).
Heck, the `MVC` controller is just an example, any class that has an internal `.ctor` will fail to be resolved in TinyIoc. AFAIK.

This is were the "issue" lies.
https://github.com/grumpydev/TinyIoC/blob/master/src/TinyIoC/TinyIoC.cs#L3708

The quickest fix would be something like this:
````csharp
const BindingFlags flags = BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Instance;

return type.GetConstructors(flags)
    .Where(x => x.IsPrivate == false)
    .OrderByDescending(ctor => ctor.GetParameters().Length);
````
Similar fix here:
https://github.com/grumpydev/TinyIoC/blob/master/src/TinyIoC/TinyIoC.cs#L3254

Also, note that now we use the same binding flags everywhere concerning `.ctor` "location".
That makes it more predictable. ;)
````csharp
t => (type.GetConstructors(BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Instance)
    .Where(x => x.IsPrivate == false)
    .Count() == 0) &&
    !(t.IsInterface() || t.IsAbstract()),
````

Anyway those are my 5cents, I'll be more than happy to create a pull request to fix this, if such possibility arrises ;)

**Comment by damianh** [comment]
+1 

@grumpydev envisage any potential side effects?

**Comment by r3db** [comment]
@damianh 
With that snippet there's no way to tell if it's `private` or `internal`, it could be **anything** other than public.
You're right about that, but does it really matter?

If something is not accessible to me do I care how private it is?
From an external point of a view, `internal`, `protected` and `private` are all the same accessibility, (they are not public, thus out of reach).

Just my 5 cents.
Your argument as to why not, (in my perspective), is similar to someone saying.
Let's ask Microsoft to remove Reflection because people may instantiate types that were not meant to be exposed.
Ok...

What I propose is an option.
**Not** something that is always on.
In fact that would probably brake a lot of already existing projects that use TinyIoC.

You either use the option or not; you do it at your own expense.
It's the user's responsibility.

Plus the case that I present here has nothing to do with 3rd party classes.
What I present here is a case where I tailor my classes in terms of accessibility to work with existing IoC frameworks.
I should't have to do that.
Why should I expose types to the outside world? Types that should never be visible to anyone.
Imagine .Net does this: They start using IoC in `mscorlib`, (crazy I know), now types like `__Cannon` start to be visible.
Me has the consumer, I have no idea these classes were not meant to be consumed from the outside, at best I'll have an array of design issues.
Anyway, this goes long already...

For me it's a case of flexibility, that most IoCs out there fail to provide.
Just my 5 cents. ;)

**Comment by damianh** [comment]
The types are still internal, just the ctors are either public OR you
register custom factory method for internal ctors.

**Comment by damianh** [comment]
If there a BindingFlags.Internal existed, I'd be on-board with the
suggestion.

**Comment by r3db** [comment]
> The types are still internal

You got a point there.
It's just the constructors not the types.
Plus I can register a custom factory method.

I'm ok with that. ;)
