### ISSUE TITLE
Add support for new coreclr

### ISSUE THREAD

**Issue by kevinkuszyk** [grumpydev/TinyIoC#77]
Have you considered support for running on the new coreclr?

I have hacked together a version which builds, but does not run.  If this is something you are interested in and could help me fix I put together a pull request.

**Comment by niemyjski** [comment]
+1 has anyone worked on this?

**Comment by jchannon** [comment]
Its waiting on #94 to be merged. Pinging @grumpydev

**Comment by niemyjski** [comment]
Great job!
