### ISSUE TITLE
Wiki typo

### ISSUE THREAD

**Issue by jgillich** [grumpydev/TinyIoC#79]
https://github.com/grumpydev/TinyIoC/wiki/Registration---lifetimes

The text explicitly says `RegisterMultiple`, but the code uses `Register` (which doesn't compile).
```
container.Register<IMyMarkerInterface>(new[] { typeof(MyImplementationClass1), typeof(MyImplementationClass2) });

// should be

container.RegisterMultiple<IMyMarkerInterface>(new[] { typeof(MyImplementationClass1), typeof(MyImplementationClass2) });
```

**Comment by grumpydev** [comment]
The wiki is editable by anyone :)

**Comment by jgillich** [comment]
I don't think it is, at least I don't have an edit button at the usual place.

**Comment by grumpydev** [comment]
Should be there now, for some reason it was restricted to collabs :/

**Comment by jgillich** [comment]
Thanks, I edited it.
