### ISSUE TITLE
Change Registration at run time?

### ISSUE THREAD

**Issue by JohnMcAvinue** [grumpydev/TinyIoC#88]
Hi,

I have two concrete implementations for an interface. One is these is always used except for when a Demo mode is enabled. How can I change the implementation at run time when this happens? I don't see a Remove or Replace function on the container.

Thanks

**Comment by grumpydev** [comment]
Registrations overwrite the previous one for the same type. Depending on the lifetime of your objects, and whether the "demo" mode can be toggled at runtime, you may be better with some sort of proxy object though.
